version: "3.8"

services:
  ticket_db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${APP_DB_PORT}:${APP_DB_PORT}"
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data


  user_mgt_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT_EXTERNAL}:${APP_SERVER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: ${DATA_SOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${APP_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${DB_DDL_AUTO}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${DRIVE_CLASS_NAME}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${DB_DIALECT}
      SPRING_JPA_SHOW_SQL: ${DB_SHOW_SQL}
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: ${DB_LOG_LEVEL}
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      SPRING_MVC_PATHMATCH_MATCHING_STRATEGY: ${SPRING_MVC_PATHMATCH_MATCHING_STRATEGY}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
      FROM_EMAIL: ${FROM_EMAIL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_CLAIM_KEY: ${JWT_CLAIM_KEY}
    depends_on:
      - user_mgt_db
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
